### ISSUE TITLE
[BUG]获取的API不能直接使用

### ISSUE THREAD

**Issue by huntersxy** [Melon-Studio/McHMR-Updater-v2#34]
![image](https://github.com/user-attachments/assets/58ca4305-1ad8-4eb5-9b5d-1a4e344dce06)
{"code":2,"msg":"系统内部错误：The request was rejected because the URL contained a potentially malicious String \"//\""}
![image](https://github.com/user-attachments/assets/4b8024a5-a4d7-4cff-9e6d-06e608e78dc6)
同时本地config中存在相同问题
![image](https://github.com/user-attachments/assets/2a091cc9-a979-444e-b19e-669ff2327ec3)

将//手动改为/方可使用

**Comment by 6get-xiaofan** [comment]
详细查看前端部署第三条
https://doc.dooper.top/docs/guide/manual-deployment
后面优化这部分

**Comment by 6get-xiaofan** [comment]
已解决
