### ISSUE TITLE
[BUG]获取新版本后进行下载时,显示下载成功而实际上并没有下载

### ISSUE THREAD

**Issue by huntersxy** [Melon-Studio/McHMR-Updater-v2#35]
更新器没有日志无法提供,可复现.

**Comment by 6get-xiaofan** [comment]
请提供复现过程

**Comment by huntersxy** [comment]
![f538ae5dc81ce983ba88e63fa0e12e94](https://github.com/user-attachments/assets/3bc058c0-26b2-45af-a3a6-2823bce3357e)
![image](https://github.com/user-attachments/assets/1fe0cba8-79cf-4a9a-a8c9-baa6b86e267f)
![6b7a0d87ce9111cf336b3ad4a9ac43d2](https://github.com/user-attachments/assets/4d8e25e1-3156-44d5-b814-a9099cf0d1cb)
![ebb0d3f38ed6de3f17842166eade547c](https://github.com/user-attachments/assets/f630ed61-e46f-4a62-8071-6597436ddcd8)
![e0ce2f2f55e623ac4d14c6f74f9bf9a1](https://github.com/user-attachments/assets/ba771d6e-a07f-426a-8332-453e7bdac617)
![d84c31e43fb2e8d0dbc3c30260fbf3f4](https://github.com/user-attachments/assets/d5ec2bd5-c3cd-4346-a614-34b9a5dc5e80)
↓后续为视频
https://github.com/user-attachments/assets/efafe363-684b-45d7-8d5c-dfd149eb9405

**Comment by huntersxy** [comment]
[1.log](https://github.com/user-attachments/files/17614388/1.log)
houd后端部分log

**Comment by fusheng357** [comment]
此bug已在新版本中修复，请等待新版本发布
